# Generated by Django 3.2.12 on 2022-03-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododiary',
            name='todo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
