# Generated by Django 3.2.12 on 2022-03-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_tododiary_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododiary',
            name='todos',
            field=models.JSONField(default='{}'),
        ),
    ]
