# Generated by Django 3.2.12 on 2022-03-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_remove_tododiary_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododiary',
            name='todos_check',
            field=models.JSONField(default=dict),
        ),
    ]
