# Generated by Django 3.2.12 on 2022-03-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_tododiary_todos_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tododiary',
            name='todos_check',
        ),
    ]
