# Generated by Django 3.2.12 on 2022-03-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_remove_tododiary_todos_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododiary',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
